steps:
  # 1. Clone repository
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - https://github.com/fariborzfallahzadeh/gcp-repo-01.git

  # 2. Build Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}
      - '.'

  # 3. Push Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}

substitutions:
  _PROJECT_ID: handy-limiter-466809-s2
  _CINAME: dke-image
  _VERSION: v1.0

options:
  logging: CLOUD_LOGGING_ONLY
