steps:
  # ۱. کلون کردن سورس‌کد از GitHub
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/fariborzfallahzadeh/gcp-repo-01.git']

  # ۲. ساخت Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/gcp-repo-01', '.']

  # ۳. Push کردن ایمیج به Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/gcp-repo-01']

  # ۴. تنظیم احراز هویت برای GKE
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - container
      - clusters
      - get-credentials
      - $_CLUSTER_NAME
      - --zone=$_ZONE
      - --project=$PROJECT_ID

  # ۵. بروزرسانی Deployment در GKE
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: kubectl
    args:
      - apply
      - -f
      - k8s-deployment.yaml

  # ۶. بروزرسانی Service برای LoadBalancer در GKE
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: kubectl
    args:
      - apply
      - -f
      - k8s-service.yaml

  # ۷. بررسی سرویس و دریافت External IP
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: kubectl
    args: ['get', 'svc', 'gcp-repo-01-service']

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/gcp-repo-01'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _CLUSTER_NAME: "cicd-cluster"
  _ZONE: "us-central1-a"
  _DEPLOYMENT_NAME: "gcp-repo-01"
