steps:
  - name: gcr.io/cloud-builders/git
    args: ['clone', 'https://github.com/fariborzfallahzadeh/gcp-repo-01.git']

  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/${CINAME}:${VERSION}', '.']

  - name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/${PROJECT_ID}/${CINAME}:${VERSION}']

substitutions:
  PROJECT_ID: ascendant-woods-452816-t8
  CINAME: dke-image
  VERSION: v1.0

options:
  logging: CLOUD_LOGGING_ONLY
