steps:
  # ۱. ساخت Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/gcp-repo-01', '.']

  # ۲. Push کردن ایمیج به Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/gcp-repo-01']

  # ۳. دیپلوی روی Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - gcp-repo-01
      - --image=us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/gcp-repo-01
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated

  # ۴. افزودن دسترسی `allUsers` به Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - services
      - add-iam-policy-binding
      - gcp-repo-01
      - --member=allUsers
      - --role=roles/run.invoker
      - --region=us-central1

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/gcp-repo-01'

options:
  logging: CLOUD_LOGGING_ONLY
