steps:
  # مرحله ۱: ساخت Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/gcp-repo-01', '.']

  # مرحله ۲: Push کردن به Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/gcp-repo-01']

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/gcp-repo-01'

options:
  logging: CLOUD_LOGGING_ONLY  # ارسال لاگ‌ها فقط به Cloud Logging
